apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-service
spec:
  rules:
    - http:
        paths:
          - path: /
            backend:
              serviceName: football-cluster-ip-service
              servicePort: 8080
